;; Set up package.el to work with MELPA
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)

;; Init Evil
(unless (package-installed-p 'evil)
  (package-install 'evil))
(require 'evil)
(evil-mode 1)

;; Init SLIME
(unless (package-installed-p 'slime)
  (package-install 'slime))
(require 'slime-autoloads)
(setq inferior-lisp-program "/opt/homebrew/bin/sbcl")

;; Init ORG
(unless (package-installed-p 'org)
  (package-install 'org))

;; Enable auto paren
(setq electric-pair-mode t)

;; Some autogenerated stuff
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages '(slime evil))
 '(scheme-program-name "/opt/homebrew/bin/scheme"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
